'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const cli = path.resolve(__dirname, '../tools/very-hard-test.cjs');
// A synthetic 1x1 PNG for filesystem tests, never evidence of a played game.
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jL1sAAAAASUVORK5CYII=', 'base64');
test('CLI preserves records, detects evidence edits, and never marks one win complete', t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'tio-vh-protocol-test-'));
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  const campaign = path.join(directory, 'campaign.json');
  const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
  assert.equal(run('init', campaign, 'A', 'B', 'C', 'D').status, 0);
  assert.equal(run('init', campaign, 'A', 'B', 'C', 'D').status, 1, 'must not overwrite a plan');
  let result = run('report', campaign);
  assert.equal(result.status, 2);
  assert.equal(JSON.parse(result.stdout).completed, 0);
  const template = JSON.parse(fs.readFileSync(campaign + '.result-template.json', 'utf8'));
  const plan = JSON.parse(fs.readFileSync(campaign, 'utf8'));
  template.outcome = 'win';
  template.startedAt = new Date(Date.parse(plan.createdAt) + 1000).toISOString();
  template.endedAt = new Date(Date.parse(plan.createdAt) + 61000).toISOString();
  fs.writeFileSync(path.join(directory, template.evidence.start.path), png);
  fs.writeFileSync(path.join(directory, template.evidence.finish.path), png);
  const entry = path.join(directory, 'result.json');
  fs.writeFileSync(entry, JSON.stringify(template));
  result = run('record', campaign, entry);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(result.stdout).status, 'incomplete');
  const backup = JSON.parse(fs.readFileSync(campaign + '.before-match-1.json', 'utf8'));
  assert.equal(backup.results.length, 0);
  const recorded = JSON.parse(fs.readFileSync(campaign, 'utf8'));
  assert.match(recorded.results[0].evidence.finish.sha256, /^[a-f0-9]{64}$/);
  assert.equal(run('record', campaign, entry).status, 1, 'cannot record a duplicate win');
  assert.equal(run('report', campaign).status, 2, 'one win is not a completed campaign');
  fs.appendFileSync(path.join(directory, template.evidence.finish.path), 'tampering');
  result = run('report', campaign);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Evidence changed/);
});
test('CLI rejects a text file masquerading as a screenshot without altering the plan', t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'tio-vh-invalid-evidence-'));
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  const campaign = path.join(directory, 'campaign.json');
  const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
  assert.equal(run('init', campaign, 'A', 'B', 'C', 'D').status, 0);
  const template = JSON.parse(fs.readFileSync(campaign + '.result-template.json', 'utf8'));
  fs.writeFileSync(path.join(directory, template.evidence.start.path), 'not an image');
  fs.writeFileSync(path.join(directory, template.evidence.finish.path), png);
  const entry = path.join(directory, 'result.json');
  fs.writeFileSync(entry, JSON.stringify(template));
  const result = run('record', campaign, entry);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /PNG\/JPEG/);
  assert.equal(JSON.parse(fs.readFileSync(campaign, 'utf8')).results.length, 0);
});
